# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d589036e1028c377d869af4e070e809662107a56a290816f6eceb8c486d89ea7bf61e89ac35867d3184eecaa1128816012407257fd1fe88e24446383e1ada68

test:
  secret_key_base: 87ac8c743e8fa9819ad12aae284d7fc3e9939cae0bd2fc2ad6083560632df12d87e68c4346328594c512fdf22e4d57ae4b72f8f310ef3a9310adf312b0875ece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
